### ISSUE TITLE
help for implement

### ISSUE THREAD

**Issue by johnfelipe** [konstantint/talkofeurope-wordclouds#1]
Hi, is posible implementation for this http://concejodemedellin.felipeurrego.com/speeches

**Comment by konstantint** [comment]
Hi, I don't think I would currently have the time to deal with that. (I might have some free time later in autumn, but certainly not now). In any case, I'm ready to assist you - there is probably not too much that needs to be done to visualize that corpus instead.

In principle, if you extract the corpus in the form of a csv table with, say, three columns: "Speaker", "Date" and "Text" (as well as any other columns you think might be useful, e.g. "country", if there is one known, or perhaps "Session"), I would be easier to help you for me.

**Comment by johnfelipe** [comment]
Building csv, give me your email adress for send csv file please, tnks

**Comment by konstantint** [comment]
kt@ut.ee

**Comment by johnfelipe** [comment]
Done send you with subject **My csv**

**Comment by konstantint** [comment]
OK, so I actually found out that it would be easier for me to do the bulk of the conversion myself rather than have to explain it to you in detail. Hence, here is the forked version of this project that is adapted to your dataset: https://github.com/konstantint/talkofacta. I have ran the feature extraction code, so the significant words computed by month, by hansard and by speaker are available in the `talkofactaweb/data/resultsdb.sqlite` file, that is commited into the repository (I also commited the csv file you provided with some modifications, hope that's not a problem).

I have adapted the webapp to show wordclouds by hansard and by month. You can launch it in debug mode by checking out the repository, and then running

```
python bootstrap.py
bin/buildout
export CONFIG=sample_settings.py
bin/talkofacta-web run
```

Here is how this app looks currently: http://europe.all.my:8000/by_hansard
As I have no idea what the discussions were about nor do I understand Spanish, I have no clue whether the results make much sense.

I leave the implementation of the by_speaker page up to you, but it should be a straightforward matter of replicating some code from `views.py` and the `by_hansard.html` template.

**Comment by johnfelipe** [comment]
How push spanish translation?

**Comment by konstantint** [comment]
You are free to translate the template html files to your liking.

**Comment by johnfelipe** [comment]
How convert you to talkofactaweb/data/resultsdb.sqlite?

**Comment by konstantint** [comment]
I did not understand the question. That file is an sqlite database that has the significantly overrepresented words already computed for your dataset.

**Comment by johnfelipe** [comment]
In this is cheatsheet installation process https://docs.google.com/document/d/1PXgKMzoZtVfUHDj--S9yp8JhxoVNW7UZNqFDzsxC7O4/edit?usp=sharing

**Comment by johnfelipe** [comment]
Give a gmail account for help me to create and publish here later

**Comment by konstantint** [comment]
The whole installation process is already described in the comment above (indeed, up to the point of you needing to install python 2.7 and clone the repository). If you want to run the webserver in production you might use something like `gunicorn` instead of the debug server. I.e. the whole deployment would then consist of the following sequence of actions:

```
git clone https://github.com/konstantint/talkofacta.git
cd talkofacta
python bootstrap.py
bin/buildout
export CONFIG=sample_config.py
bin/gunicorn --paste sample_pasteconfig.ini
```

You might want to edit the lines `sample_pasteconfig.ini` that specifies the host and port at which the application will be served (e.g. change host to `0.0.0.0` if you want to access it from computers besides your localhost).

**Comment by johnfelipe** [comment]
```
notroot@felipeurrego:~/talkofacta$ bin/gunicorn --paste sample_pasteconfig.ini
Traceback (most recent call last):
  File "bin/gunicorn", line 57, in <module>
    sys.exit(gunicorn.app.wsgiapp.run())
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/arbiter.py", line 114, in setup
    self.app.wsgi()
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=None)
  File "/home/notroot/talkofacta/eggs/gunicorn-19.3.0-py2.7.egg/gunicorn/app/pasterapp.py", line 71, in load_pasteapp
    global_conf=global_conf)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 271, in loadobj
    global_conf=global_conf)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 320, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 454, in get_context
    section)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 476, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 406, in get_context
    global_conf=global_conf)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 296, in loadcontext
    global_conf=global_conf)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 328, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 620, in get_context
    object_type, name=name)
  File "/home/notroot/talkofacta/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 640, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/home/notroot/talkofacta/eggs/setuptools-14.3.1-py2.7.egg/pkg_resources/__init__.py", line 921, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/notroot/talkofacta/eggs/setuptools-14.3.1-py2.7.egg/pkg_resources/__init__.py", line 808, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: talkofeuropeweb
```

**Comment by konstantint** [comment]
Do a git pull and repeat

**Comment by johnfelipe** [comment]
now this:

```
notroot@felipeurrego:~/talkofacta$ bin/gunicorn --paste sample_pasteconfig.ini
[2015-05-26 20:04:57 +0000] [3849] [INFO] Starting gunicorn 19.3.0
[2015-05-26 20:04:57 +0000] [3849] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2015-05-26 20:04:57 +0000] [3849] [ERROR] Retrying in 1 second.
[2015-05-26 20:04:58 +0000] [3849] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2015-05-26 20:04:58 +0000] [3849] [ERROR] Retrying in 1 second.
[2015-05-26 20:04:59 +0000] [3849] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2015-05-26 20:04:59 +0000] [3849] [ERROR] Retrying in 1 second.
[2015-05-26 20:05:00 +0000] [3849] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2015-05-26 20:05:00 +0000] [3849] [ERROR] Retrying in 1 second.
[2015-05-26 20:05:01 +0000] [3849] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2015-05-26 20:05:01 +0000] [3849] [ERROR] Retrying in 1 second.
    [2015-05-26 20:05:02 +0000] [3849] [ERROR] Can't connect to ('0.0.0.0', 8000)
```

**Comment by johnfelipe** [comment]
solved change 8000 to 8001

**Comment by konstantint** [comment]
That was because some other service was using port 8000.

I'll close this issue now.
